using Normal.Realtime;
using Normal.Realtime.Serialization;

namespace HYDAC.Scripts.NET
{
    [RealtimeModel]
    public partial class RoomStateNCModel 
    {
        [RealtimeProperty(1, true, true)]
        private string _currentAssemblyName;
        
        [RealtimeProperty(2, true, true)]
        private bool _islocked;
    }
}

/* ----- Begin Normal Autogenerated Code ----- */
namespace HYDAC.Scripts.NET {
    public partial class RoomStateNCModel : RealtimeModel {
        public string currentAssemblyName {
            get {
                return _currentAssemblyNameProperty.value;
            }
            set {
                if (_currentAssemblyNameProperty.value == value) return;
                _currentAssemblyNameProperty.value = value;
                InvalidateReliableLength();
                FireCurrentAssemblyNameDidChange(value);
            }
        }
        
        public bool islocked {
            get {
                return _islockedProperty.value;
            }
            set {
                if (_islockedProperty.value == value) return;
                _islockedProperty.value = value;
                InvalidateReliableLength();
                FireIslockedDidChange(value);
            }
        }
        
        public delegate void PropertyChangedHandler<in T>(RoomStateNCModel model, T value);
        public event PropertyChangedHandler<string> currentAssemblyNameDidChange;
        public event PropertyChangedHandler<bool> islockedDidChange;
        
        public enum PropertyID : uint {
            CurrentAssemblyName = 1,
            Islocked = 2,
        }
        
        #region Properties
        
        private ReliableProperty<string> _currentAssemblyNameProperty;
        
        private ReliableProperty<bool> _islockedProperty;
        
        #endregion
        
        public RoomStateNCModel() : base(null) {
            _currentAssemblyNameProperty = new ReliableProperty<string>(1, _currentAssemblyName);
            _islockedProperty = new ReliableProperty<bool>(2, _islocked);
        }
        
        protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
            _currentAssemblyNameProperty.UnsubscribeCallback();
            _islockedProperty.UnsubscribeCallback();
        }
        
        private void FireCurrentAssemblyNameDidChange(string value) {
            try {
                currentAssemblyNameDidChange?.Invoke(this, value);
            } catch (System.Exception exception) {
                UnityEngine.Debug.LogException(exception);
            }
        }
        
        private void FireIslockedDidChange(bool value) {
            try {
                islockedDidChange?.Invoke(this, value);
            } catch (System.Exception exception) {
                UnityEngine.Debug.LogException(exception);
            }
        }
        
        protected override int WriteLength(StreamContext context) {
            var length = 0;
            length += _currentAssemblyNameProperty.WriteLength(context);
            length += _islockedProperty.WriteLength(context);
            return length;
        }
        
        protected override void Write(WriteStream stream, StreamContext context) {
            var writes = false;
            writes |= _currentAssemblyNameProperty.Write(stream, context);
            writes |= _islockedProperty.Write(stream, context);
            if (writes) InvalidateContextLength(context);
        }
        
        protected override void Read(ReadStream stream, StreamContext context) {
            var anyPropertiesChanged = false;
            while (stream.ReadNextPropertyID(out uint propertyID)) {
                var changed = false;
                switch (propertyID) {
                    case (uint) PropertyID.CurrentAssemblyName: {
                        changed = _currentAssemblyNameProperty.Read(stream, context);
                        if (changed) FireCurrentAssemblyNameDidChange(currentAssemblyName);
                        break;
                    }
                    case (uint) PropertyID.Islocked: {
                        changed = _islockedProperty.Read(stream, context);
                        if (changed) FireIslockedDidChange(islocked);
                        break;
                    }
                    default: {
                        stream.SkipProperty();
                        break;
                    }
                }
                anyPropertiesChanged |= changed;
            }
            if (anyPropertiesChanged) {
                UpdateBackingFields();
            }
        }
        
        private void UpdateBackingFields() {
            _currentAssemblyName = currentAssemblyName;
            _islocked = islocked;
        }
        
    }
}
/* ----- End Normal Autogenerated Code ----- */
